<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/forms.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/angular.min.js'))
        ?>
        <script> var app = angular.module('Front', []); </script>
    </head>
    <body ng-app="Front">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li><a href="./" class="navbar-brand"><?= $this->translate('layout.application.name') ?></a></li>
                    <li><a href="./inscription"><?= $this->translate('menu.authentication') ?></a></li>
                    <li><a href="./connexion"><?= $this->translate('menu.connexion') ?></a></li>
                    <li><a href="./administration"><?= $this->translate('menu.administration') ?></a> </li>
                </ul>
            </div>
        </div>
    </div>

        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>