<?= $this->doctype() ?>

<?php
    $ConnectedUserId = \Application\Models\UsersModel::getConnectedUser();
    $UserModel = new \Application\Models\UsersModel();
    $ConnectedUser = $UserModel->getUserById($ConnectedUserId);
    $flashMessenger = new \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/forms.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/angular.min.js'))
        ?>
        <script> var app = angular.module('Front', []); </script>
    </head>
    <body ng-app="Front">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li><a href="./" class="navbar-brand"><?= $this->translate('layout.application.name') ?></a></li>
                    <li><a href="./inscription"><?= $this->translate('menu.authentication') ?></a></li>

                    <?php if (!\Application\Models\UsersModel::isConnected()) : ?>
                        <li><a id='showLogin' href="javascript:;"><?= $this->translate('menu.connexion') ?></a> </li>
                    <?php else: ?>
                        <li><a>Bonjour <?= $ConnectedUser->getFullName(); ?></a></li>
                        <li><a href="./deconnexion"><?= $this->translate('menu.disconnect') ?></a> </li>
                    <?php endif; ?>

                    <li></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="./administration"><?= $this->translate('menu.administration') ?></a> </li>
                </ul>
            </div>
            <div id="authentication"></div>
        </div>
    </div>
    <div class="col-md-3"></div>

    <?= $this->getMessages(\Application\Helpers\MessagesHelper::DANGER); ?>

    <div class="row"></div>
        <div class="container">
            <?= $this->content ?>
        </div>

        <?= $this->inlineScript() ?>
    </body>
</html>

<script>

    $('#showLogin').click(function() {
        $.ajax({
            url: "<?= $this->url('login');?>",
            method: 'GET',
        }).then(function(html) {
            $('#authentication').html(html);
        });
    });

    app.controller('MessagesController', function($scope, $http) {
        $http.get("<?= $this->url('getMessages');?>")
            .then(function(response) {
                $scope.messages = response.data;
                console.log($scope.messages);
            });
    });

</script>