<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- Le styles -->
        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
