<?php $form = $this->form; ?>

<?php
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger">');
$helper->setMessageCloseString('</div>');
?>

<div class="col-md-3"></div>

<div class="col-md-6">
    <div class="jumbotron">
        <h3><i class="fa fa-users" aria-hidden="true"></i> Se connecter à <?= $this->translate('layout.application.name') ?></h3>
        <hr>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formRow($form->get('login')) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('password')) ?>
        </div>

        <?= $this->formButton($form->get('validate')) ?>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
<table ng-controller="UsersController" class="table table-striped" id="users">
    <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
        <th>Mot de Passe</th>
    </tr>
    <tr ng-repeat="user in users">
        <td>{{user.firstname}}</td>
        <td>{{user.lastname}}</td>
        <td>{{user.email}}</td>
        <td>{{user.password}}</td>
    </tr>
</table>

<script>


    app.controller('UsersController', function($scope, $http) {
        $http.get("<?= $this->url('users', array("id", 1));?>")
            .then(function(response) {
                $scope.users = response.data;
                console.log($scope.users);
            });
    });

    $('#ValidLoginForm').click(function() {
        $.ajax({
            url: "<?= $this->url('login');?>",
            method: 'POST',
            data: $('#registerForm').serialize()
        }).then(function(data) {
            console.log(data);
        });
    })

</script>
