<form id='registerForm' class="navbar-form navbar-right">

    <input id='login' type="text" name='login' class="form-control" placeholder="Adresse e-mail ou mobile">
    <div class="input-group">
        <input id='password' type="password" name='password' class="form-control" placeholder="Mot de passe">
        <span class="input-group-btn">
            <button id='ValidLoginForm' class="btn btn-primary" type="button">Connexion</button>
        </span>
    </div><!-- /input-group -->

</form>

<script>

    $('#ValidLoginForm').click(function() {
        $.ajax({
            url: "<?= $this->url('login');?>",
            method: 'POST',
            data: $('#registerForm').serialize()
        }).then(function(data) {
            console.log(data);
            if (data.isConnected) {
                window.location = "<?= $this->url('home');?>";
            }
        });
    })

</script>
