<?php $form = $this->form; ?>

<?php
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger">');
$helper->setMessageCloseString('</div>');
?>

<div class="col-md-3"></div>

<div class="col-md-6">
    <div class="jumbotron">
        <h3><i class="fa fa-users" aria-hidden="true"></i> Se connecter à <?= $this->translate('layout.application.name') ?></h3>
        <hr>

        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formRow($form->get('login')) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('password')) ?>
        </div>

        <?= $this->formButton($form->get('validate')) ?>

        <?= $this->form()->closeTag() ?>
    </div>
</div>

<h5>Liste des utilisateurs enregistrés : </h5>
<div id="users" class="jumbotron">

</div>

<script>

    $.ajax({
        url: "<?= $this->url('users', array("id", 1));?>",
        method: 'GET',
        dataType: "json"
    }).then(function(data) {
        $.each( data, function( key, val ) {
            $('#users').append( "<li>" + val.firstname + " " + val.lastname + " " + val.email + " " + val.password + "</li>" );
        });

    });

    $('#ValidLoginForm').click(function() {
        $.ajax({
            url: "<?= $this->url('login');?>",
            method: 'POST',
            data: $('#loginForm').serialize()
        }).then(function(data) {
            console.log(data);
        });
    })

</script>
