<?php $form = $this->form; ?>
<?php $form->setAttribute('action', $this->url('authentication')) ?>

<?php
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger">');
$helper->setMessageCloseString('</div>');
?>
<div class="col-md-3"></div>
<div class="col-md-6">
    <div class="jumbotron">
        <h3><i class="fa fa-users" aria-hidden="true"></i> Créer un compte</h3>
        <hr>

        <?= $this->form()->openTag($form) ?>

            <div class="form-group">
                <?= $this->formRow($form->get('firstname')) ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('lastname')) ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('email')) ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('password')) ?>
            </div>

            <?= $this->formButton($form->get('validate')) ?>

        <?= $this->form()->closeTag() ?>
    </div>
</div>

<script>
    $('#ValidRegisterForm').click(function() {
        $.ajax({
            url: "<?= $this->url('authentication');?>",
            method: 'POST',
            data: $('#registerForm').serialize()
        }).then(function(data) {
            console.log(data);
        });
    })
</script>


