<div class="col-md-12">
    <div class="jumbotron">
        <h2><b>Accueil</b> - This opera's as lousy as it is brilliant!</h3>
        <hr>
        <h5>Cum haec taliaque sollicitas eius aures everberarent expositas semper eius modi rumoribus et patentes, varia animo tum miscente consilia, tandem id ut optimum factu elegit: et Vrsicinum primum ad se venire summo cum honore mandavit ea specie ut pro rerum tunc urgentium captu disponeretur concordi consilio, quibus virium incrementis Parthicarum gentium a arma minantium impetus frangerentur.</h5>
    </div>
</div>

<div class="row"></div>

<div class="col-md-6">
    <div class="jumbotron">
        <h3>Incidentally, you have a dime.</h3>
        <hr>
        <h5>Oh, but you can. But you may have to metaphorically make a deal with the devil. And by "devil", I mean Robot Devil. And by "metaphorically", I mean get your coat. That's not soon enough! Oh, how awful. Did he at least die painlessly? …To shreds, you say. Well, how is his wife holding up? …To shreds, you say.</h5>
        <h5>The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate. I'm just glad my fat, ugly mama isn't alive to see this day. Now that the, uh, garbage ball is in space, Doctor, perhaps you can help me with my sexual inhibitions?</h5>
        <h5>Yes, I saw. You were doing well, until everyone died. Look, last night was a mistake. They're like sex, except I'm having them! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life.</h5>
    </div>
</div>

<div class="col-md-6">
    <div class="jumbotron">
        <h3>Incidentally, you have a dime.</h3>
        <hr>
        <h5>Oh, but you can. But you may have to metaphorically make a deal with the devil. And by "devil", I mean Robot Devil. And by "metaphorically", I mean get your coat. That's not soon enough! Oh, how awful. Did he at least die painlessly? …To shreds, you say. Well, how is his wife holding up? …To shreds, you say.</h5>
        <h5>The alien mothership is in orbit here. If we can hit that bullseye, the rest of the dominoes will fall like a house of cards. Checkmate. I'm just glad my fat, ugly mama isn't alive to see this day. Now that the, uh, garbage ball is in space, Doctor, perhaps you can help me with my sexual inhibitions?</h5>
        <h5>Yes, I saw. You were doing well, until everyone died. Look, last night was a mistake. They're like sex, except I'm having them! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life.</h5>
    </div>
</div>