<?php $form = $this->form; ?>

<?= $this->form()->openTag($form) ?>

<div class="panel panel-primary">
    <div class="panel-heading">
        Créer un compte
    </div>
    <div class="panel-body">
        <div class="form-group">
            <?= $this->formRow($form->get('firstname')) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('lastname')) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('email')) ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('password')) ?>
        </div>
    </div>

    <div class="panel-footer">
        <?= $this->formButton($form->get('Validate')) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
