<div class="col-md-12">
    <div class="jumbotron">
        <h2><b>Accueil</b> - This opera's as lousy as it is brilliant!</h3>
        <hr>
        <h5>Cum haec taliaque sollicitas eius aures everberarent expositas semper eius modi rumoribus et patentes, varia animo tum miscente consilia, tandem id ut optimum factu elegit: et Vrsicinum primum ad se venire summo cum honore mandavit ea specie ut pro rerum tunc urgentium captu disponeretur concordi consilio, quibus virium incrementis Parthicarum gentium a arma minantium impetus frangerentur.
        coucou</h5>
    </div>
</div>
